- name: Copying Mysql Repo  
  ansible.builtin.copy:
    src: mysql.repo 
    dest: /etc/yum.repos.d/mysql.repo 

- name: Installing MySQL 
  ansible.builtin.package:
    name: mysql-community-server
    state: present  

- name: Starting MySQL
  ansible.builtin.service:
    name: mysqld
    state: started          
    enabled: yes 

- name: Loading the file from the remote node
  ansible.builtin.slurp:
    src: /var/log/mysqld.log
  register: mysql_log   

- name: Print returned information
  ansible.builtin.debug:
    msg: "{{ mysql_log['content'] | b64decode | regex_findall('.*temporary password.*') }}"

# - name: Declaring the facts
#   ansible.builtin.set_facts:
#       DEFAULT_PASSWORD: "{{}}"